import logging
import threading
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi_cache import FastAPICache
from fastapi_cache.backends.inmemory import InMemoryBackend
from fastapi.middleware.cors import CORSMiddleware
from slowapi import _rate_limit_exceeded_handler
from slowapi.errors import RateLimitExceeded
from slowapi.middleware import SlowAPIMiddleware
from services.rate_limiter import limiter
from services import task_services
from db.database import SessionLocal
from routes import ROUTERS
from db.models.metrics_models import *

# --- Ensure root path is importable ---
import sys, os
ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
if ROOT_DIR not in sys.path:
    sys.path.insert(0, ROOT_DIR)


# For in-memory caching
# If you want to use Redis (uncomment and configure):
# from fastapi_cache.backends.redis import RedisBackend
# from redis import asyncio as aioredis


# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

@asynccontextmanager
async def lifespan(app: FastAPI):
    # --- Startup ---
    FastAPICache.init(InMemoryBackend(), prefix="fastapi-cache")

    # Background thread stubs (no-op, replaced by real logic in task_services.py)
    def handle_recurrence(*args, **kwargs):
        logger.info("[Recurrence] Checking completed tasks for recurrence...")
        logger.info("[Recurrence] Cycle complete.")

    def check_reminders(*args, **kwargs):
        logger.info("[Reminders] Checking pending reminders...")
        logger.info("[Reminders] Check complete.")

    threading.Thread(target=handle_recurrence, daemon=True).start()
    threading.Thread(target=check_reminders, daemon=True).start()
    logger.info("Background tasks initialized (ok).")

    # Seed system identity
    from db.models.author_model import AuthorDB
    from datetime import datetime
    db = SessionLocal()
    try:
        system_id = "author-system"
        existing = db.query(AuthorDB).filter_by(id=system_id).first()
        if not existing:
            system_author = AuthorDB(
                id=system_id,
                name="A.I.N.D.Y. System",
                platform="Internal Core",
                notes="Autogenerated identity for runtime self-reference.",
                joined_at=datetime.utcnow(),
                last_seen=datetime.utcnow(),
            )
            db.add(system_author)
            db.commit()
            logger.info("Seeded system author: A.I.N.D.Y. System")
        else:
            existing.last_seen = datetime.utcnow()
            db.commit()
            logger.info("System author already present, timestamp refreshed.")
    except Exception as e:
        logger.warning(f"System identity seed failed (non-fatal): {e}")
    finally:
        db.close()

    yield
    # --- Shutdown (nothing needed currently) ---


app = FastAPI(title="A.I.N.D.Y. Memory Bridge", lifespan=lifespan)

# Rate limiting — protects AI/expensive endpoints from abuse
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)
app.add_middleware(SlowAPIMiddleware)

for route in ROUTERS:
    app.include_router(route)

# CORS — explicit origins only (wildcard + credentials is a security violation)
import os as _os
_ALLOWED_ORIGINS = [
    o.strip()
    for o in _os.getenv(
        "ALLOWED_ORIGINS",
        "http://localhost:5173,http://localhost:3000,http://localhost:5000",
    ).split(",")
    if o.strip()
]
app.add_middleware(
    CORSMiddleware,
    allow_origins=_ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "DELETE", "OPTIONS"],
    allow_headers=["*"],
)

@app.middleware("http")
async def log_requests(request, call_next):
    logger.info(f"Request: {request.method} {request.url}")
    response = await call_next(request)
    logger.info(f"Response: {response.status_code}")
    return response

@app.get("/")
def home():
    return {"message": "A.I.N.D.Y. API is running!"}