"""Authorship app initialization hooks."""

from __future__ import annotations

from datetime import datetime


def seed_authorship(context: dict) -> None:
    if context.get("is_testing"):
        return

    session_factory = context.get("session_factory")
    if session_factory is None:
        return

    log = context.get("log")
    db = session_factory()
    try:
        from apps.authorship.models import AuthorDB

        system_id = "author-system"
        existing = db.query(AuthorDB).filter_by(id=system_id).first()
        if not existing:
            system_author = AuthorDB(
                id=system_id,
                name="A.I.N.D.Y. System",
                platform="Internal Core",
                notes="Autogenerated identity for runtime self-reference.",
                joined_at=datetime.utcnow(),
                last_seen=datetime.utcnow(),
            )
            db.add(system_author)
            db.commit()
            if log:
                log.info("Seeded system author: A.I.N.D.Y. System")
            return

        existing.last_seen = datetime.utcnow()
        db.commit()
        if log:
            log.info("System author already present, timestamp refreshed.")
    except Exception as exc:
        if log:
            log.warning("System identity seed failed (non-fatal): %s", exc)
    finally:
        db.close()


def register(register_startup_hook) -> None:
    register_startup_hook(seed_authorship)
