"""Authorship domain bootstrap."""
from __future__ import annotations

from datetime import datetime, timezone

BOOTSTRAP_DEPENDS_ON: list[str] = []


def register() -> None:
    _register_models()
    _register_router()
    _register_response_adapters()
    _register_startup_hooks()


def _register_models() -> None:
    from AINDY.db.database import Base
    from AINDY.db.model_registry import register_models
    from AINDY.platform_layer.registry import register_symbols
    import apps.authorship.models as authorship_models

    register_models(authorship_models.register_models)
    register_symbols(
        {
            name: value
            for name, value in vars(authorship_models).items()
            if isinstance(value, type) and getattr(value, "metadata", None) is Base.metadata
        }
    )


def _register_router() -> None:
    from AINDY.platform_layer.registry import register_router
    from apps.authorship.routes.authorship_router import router as authorship_router
    register_router(authorship_router)


def _register_response_adapters() -> None:
    from AINDY.platform_layer.registry import register_response_adapter
    from apps._adapters import raw_json_adapter
    register_response_adapter("authorship", raw_json_adapter)


def _register_startup_hooks() -> None:
    from AINDY.platform_layer.registry import register_startup_hook
    register_startup_hook(seed_authorship)


def seed_authorship(context: dict) -> None:
    if context.get("is_testing"):
        return

    session_factory = context.get("session_factory")
    if session_factory is None:
        return

    log = context.get("log")
    db = session_factory()
    try:
        from apps.authorship.models import AuthorDB

        system_id = "author-system"
        existing = db.query(AuthorDB).filter_by(id=system_id).first()
        if not existing:
            system_author = AuthorDB(
                id=system_id,
                name="A.I.N.D.Y. System",
                platform="Internal Core",
                notes="Autogenerated identity for runtime self-reference.",
                joined_at=datetime.now(timezone.utc),
                last_seen=datetime.now(timezone.utc),
            )
            db.add(system_author)
            db.commit()
            if log:
                log.info("Seeded system author: A.I.N.D.Y. System")
            return

        existing.last_seen = datetime.now(timezone.utc)
        db.commit()
        if log:
            log.info("System author already present, timestamp refreshed.")
    except Exception as exc:
        if log:
            log.warning("System identity seed failed (non-fatal): %s", exc)
    finally:
        db.close()
