"""add master_plans table

Revision ID: 1a085e32efd4
Revises: e52a1f667323
Create Date: 2026-02-14 14:32:28.462586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a085e32efd4'
down_revision: Union[str, None] = 'e52a1f667323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_contributions', sa.Integer(), nullable=True),
    sa.Column('human_contributions', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_efficiencies_id'), 'ai_efficiencies', ['id'], unique=False)
    op.create_table('ai_productivity_boosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasks_with_ai', sa.Float(), nullable=True),
    sa.Column('tasks_without_ai', sa.Float(), nullable=True),
    sa.Column('time_saved', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_productivity_boosts_id'), 'ai_productivity_boosts', ['id'], unique=False)
    op.create_table('attention_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_output', sa.Float(), nullable=True),
    sa.Column('platform_presence', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_values_id'), 'attention_values', ['id'], unique=False)
    op.create_table('business_growths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.Column('scaling_friction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_growths_id'), 'business_growths', ['id'], unique=False)
    op.create_table('decision_efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automated_decisions', sa.Float(), nullable=True),
    sa.Column('manual_decisions', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_efficiencies_id'), 'decision_efficiencies', ['id'], unique=False)
    op.create_table('efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focused_effort', sa.Float(), nullable=True),
    sa.Column('ai_utilization', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efficiencies_id'), 'efficiencies', ['id'], unique=False)
    op.create_table('engagement_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Float(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_rates_id'), 'engagement_rates', ['id'], unique=False)
    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('time_on_page', sa.Float(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagements_id'), 'engagements', ['id'], unique=False)
    op.create_table('execution_speeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_automations', sa.Float(), nullable=True),
    sa.Column('systemized_workflows', sa.Float(), nullable=True),
    sa.Column('decision_lag', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_speeds_id'), 'execution_speeds', ['id'], unique=False)
    op.create_table('impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.Column('conversion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impacts_id'), 'impacts', ['id'], unique=False)
    op.create_table('lost_potentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missed_opportunities', sa.Float(), nullable=True),
    sa.Column('time_delayed', sa.Float(), nullable=True),
    sa.Column('gains_from_action', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_potentials_id'), 'lost_potentials', ['id'], unique=False)
    op.create_table('master_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('duration_years', sa.Float(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_origin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_plans_id'), 'master_plans', ['id'], unique=False)
    op.create_index(op.f('ix_master_plans_version'), 'master_plans', ['version'], unique=False)
    op.create_table('memory_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_nodes_tags_gin', 'memory_nodes', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('monetization_efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('audience_size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monetization_efficiencies_id'), 'monetization_efficiencies', ['id'], unique=False)
    op.create_table('revenue_scalings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_leverage', sa.Float(), nullable=True),
    sa.Column('content_distribution', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('audience_engagement', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_scalings_id'), 'revenue_scalings', ['id'], unique=False)
    op.create_table('memory_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['memory_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_links_source', 'memory_links', ['source_node_id'], unique=False)
    op.create_index('ix_memory_links_target', 'memory_links', ['target_node_id'], unique=False)
    op.create_index('uq_memory_links_unique', 'memory_links', ['source_node_id', 'target_node_id', 'link_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_memory_links_unique', table_name='memory_links')
    op.drop_index('ix_memory_links_target', table_name='memory_links')
    op.drop_index('ix_memory_links_source', table_name='memory_links')
    op.drop_table('memory_links')
    op.drop_index(op.f('ix_revenue_scalings_id'), table_name='revenue_scalings')
    op.drop_table('revenue_scalings')
    op.drop_index(op.f('ix_monetization_efficiencies_id'), table_name='monetization_efficiencies')
    op.drop_table('monetization_efficiencies')
    op.drop_index('ix_memory_nodes_tags_gin', table_name='memory_nodes', postgresql_using='gin')
    op.drop_table('memory_nodes')
    op.drop_index(op.f('ix_master_plans_version'), table_name='master_plans')
    op.drop_index(op.f('ix_master_plans_id'), table_name='master_plans')
    op.drop_table('master_plans')
    op.drop_index(op.f('ix_lost_potentials_id'), table_name='lost_potentials')
    op.drop_table('lost_potentials')
    op.drop_index(op.f('ix_impacts_id'), table_name='impacts')
    op.drop_table('impacts')
    op.drop_index(op.f('ix_execution_speeds_id'), table_name='execution_speeds')
    op.drop_table('execution_speeds')
    op.drop_index(op.f('ix_engagements_id'), table_name='engagements')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_engagement_rates_id'), table_name='engagement_rates')
    op.drop_table('engagement_rates')
    op.drop_index(op.f('ix_efficiencies_id'), table_name='efficiencies')
    op.drop_table('efficiencies')
    op.drop_index(op.f('ix_decision_efficiencies_id'), table_name='decision_efficiencies')
    op.drop_table('decision_efficiencies')
    op.drop_index(op.f('ix_business_growths_id'), table_name='business_growths')
    op.drop_table('business_growths')
    op.drop_index(op.f('ix_attention_values_id'), table_name='attention_values')
    op.drop_table('attention_values')
    op.drop_index(op.f('ix_ai_productivity_boosts_id'), table_name='ai_productivity_boosts')
    op.drop_table('ai_productivity_boosts')
    op.drop_index(op.f('ix_ai_efficiencies_id'), table_name='ai_efficiencies')
    op.drop_table('ai_efficiencies')
    # ### end Alembic commands ###
