"""structure integrity check

Revision ID: 97ef6237e153
Revises: 4021f10066c3
Create Date: 2026-02-15 22:46:10.613692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97ef6237e153'
down_revision: Union[str, None] = '4021f10066c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_canonical_period_scope', 'canonical_metrics', ['masterplan_id', 'platform', 'scope_type', 'scope_id', 'period_type', 'period_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_canonical_period_scope', 'canonical_metrics', type_='unique')
    # ### end Alembic commands ###
