"""Add system_health_logs table

Revision ID: e52a1f667323
Revises: 03adbb4b957b
Create Date: 2025-10-24 20:27:53.494525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e52a1f667323'
down_revision: Union[str, None] = '03adbb4b957b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('components', sa.JSON(), nullable=True),
    sa.Column('api_endpoints', sa.JSON(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_health_logs_id'), 'system_health_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_health_logs_id'), table_name='system_health_logs')
    op.drop_table('system_health_logs')
    # ### end Alembic commands ###
