"""add_wait_deadline_to_flow_run

Revision ID: 225e46d1847f
Revises: 5a6b7c8d9e0f
Create Date: 2026-04-19 09:36:57.562600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '225e46d1847f'
down_revision: Union[str, None] = '5a6b7c8d9e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flow_runs', sa.Column('wait_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('flow_runs', sa.Column('error_detail', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flow_runs', 'error_detail')
    op.drop_column('flow_runs', 'wait_deadline')
    # ### end Alembic commands ###
