"""add canonical metrics telemetry table

Revision ID: 4021f10066c3
Revises: ae693412325e
Create Date: 2026-02-15 12:02:27.756754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4021f10066c3'
down_revision: Union[str, None] = 'ae693412325e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masterplan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('scope_type', sa.String(), nullable=True),
    sa.Column('scope_id', sa.String(), nullable=True),
    sa.Column('period_type', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('passive_visibility', sa.Float(), nullable=True),
    sa.Column('active_discovery', sa.Float(), nullable=True),
    sa.Column('unique_reach', sa.Float(), nullable=True),
    sa.Column('interaction_volume', sa.Float(), nullable=True),
    sa.Column('deep_attention_units', sa.Float(), nullable=True),
    sa.Column('intent_signals', sa.Float(), nullable=True),
    sa.Column('conversion_events', sa.Float(), nullable=True),
    sa.Column('growth_velocity', sa.Float(), nullable=True),
    sa.Column('audience_quality_score', sa.Float(), nullable=True),
    sa.Column('interaction_rate', sa.Float(), nullable=True),
    sa.Column('attention_rate', sa.Float(), nullable=True),
    sa.Column('intent_rate', sa.Float(), nullable=True),
    sa.Column('conversion_rate', sa.Float(), nullable=True),
    sa.Column('discovery_ratio', sa.Float(), nullable=True),
    sa.Column('growth_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['masterplan_id'], ['master_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_metrics_id'), 'canonical_metrics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_metrics_id'), table_name='canonical_metrics')
    op.drop_table('canonical_metrics')
    # ### end Alembic commands ###
