"""add user_id to tasks leadgen authors

Revision ID: 64b531720229
Revises: f3a4b5c6d7e8
Create Date: 2026-03-21 21:46:34.400840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b531720229'
down_revision: Union[str, None] = 'f3a4b5c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_authors_user_id'), 'authors', ['user_id'], unique=False)
    op.create_foreign_key(None, 'authors', 'users', ['user_id'], ['id'])
    op.add_column('leadgen_results', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_leadgen_results_user_id'), 'leadgen_results', ['user_id'], unique=False)
    op.create_foreign_key(None, 'leadgen_results', 'users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'leadgen_results', type_='foreignkey')
    op.drop_index(op.f('ix_leadgen_results_user_id'), table_name='leadgen_results')
    op.drop_column('leadgen_results', 'user_id')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_index(op.f('ix_authors_user_id'), table_name='authors')
    op.drop_column('authors', 'user_id')
    # ### end Alembic commands ###
