"""Move metrics models to db.models

Revision ID: 94bcd9284285
Revises: 4cc6abbb35cb
Create Date: 2025-10-22 12:56:54.145252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94bcd9284285'
down_revision: Union[str, None] = '4cc6abbb35cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_contributions', sa.Integer(), nullable=True),
    sa.Column('human_contributions', sa.Integer(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_efficiencies_id'), 'ai_efficiencies', ['id'], unique=False)
    op.create_table('ai_productivity_boosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasks_with_ai', sa.Float(), nullable=True),
    sa.Column('tasks_without_ai', sa.Float(), nullable=True),
    sa.Column('time_saved', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_productivity_boosts_id'), 'ai_productivity_boosts', ['id'], unique=False)
    op.create_table('attention_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_output', sa.Float(), nullable=True),
    sa.Column('platform_presence', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_values_id'), 'attention_values', ['id'], unique=False)
    op.create_table('business_growths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.Column('scaling_friction', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_growths_id'), 'business_growths', ['id'], unique=False)
    op.create_table('decision_efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automated_decisions', sa.Float(), nullable=True),
    sa.Column('manual_decisions', sa.Float(), nullable=True),
    sa.Column('processing_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_efficiencies_id'), 'decision_efficiencies', ['id'], unique=False)
    op.create_table('efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focused_effort', sa.Float(), nullable=True),
    sa.Column('ai_utilization', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('capital', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_efficiencies_id'), 'efficiencies', ['id'], unique=False)
    op.create_table('engagement_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Float(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagement_rates_id'), 'engagement_rates', ['id'], unique=False)
    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('time_on_page', sa.Float(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engagements_id'), 'engagements', ['id'], unique=False)
    op.create_table('execution_speeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_automations', sa.Float(), nullable=True),
    sa.Column('systemized_workflows', sa.Float(), nullable=True),
    sa.Column('decision_lag', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_speeds_id'), 'execution_speeds', ['id'], unique=False)
    op.create_table('impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('engagement', sa.Integer(), nullable=True),
    sa.Column('conversion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impacts_id'), 'impacts', ['id'], unique=False)
    op.create_table('lost_potentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missed_opportunities', sa.Float(), nullable=True),
    sa.Column('time_delayed', sa.Float(), nullable=True),
    sa.Column('gains_from_action', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lost_potentials_id'), 'lost_potentials', ['id'], unique=False)
    op.create_table('monetization_efficiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('audience_size', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monetization_efficiencies_id'), 'monetization_efficiencies', ['id'], unique=False)
    op.create_table('revenue_scalings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_leverage', sa.Float(), nullable=True),
    sa.Column('content_distribution', sa.Float(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('audience_engagement', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_scalings_id'), 'revenue_scalings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_scalings_id'), table_name='revenue_scalings')
    op.drop_table('revenue_scalings')
    op.drop_index(op.f('ix_monetization_efficiencies_id'), table_name='monetization_efficiencies')
    op.drop_table('monetization_efficiencies')
    op.drop_index(op.f('ix_lost_potentials_id'), table_name='lost_potentials')
    op.drop_table('lost_potentials')
    op.drop_index(op.f('ix_impacts_id'), table_name='impacts')
    op.drop_table('impacts')
    op.drop_index(op.f('ix_execution_speeds_id'), table_name='execution_speeds')
    op.drop_table('execution_speeds')
    op.drop_index(op.f('ix_engagements_id'), table_name='engagements')
    op.drop_table('engagements')
    op.drop_index(op.f('ix_engagement_rates_id'), table_name='engagement_rates')
    op.drop_table('engagement_rates')
    op.drop_index(op.f('ix_efficiencies_id'), table_name='efficiencies')
    op.drop_table('efficiencies')
    op.drop_index(op.f('ix_decision_efficiencies_id'), table_name='decision_efficiencies')
    op.drop_table('decision_efficiencies')
    op.drop_index(op.f('ix_business_growths_id'), table_name='business_growths')
    op.drop_table('business_growths')
    op.drop_index(op.f('ix_attention_values_id'), table_name='attention_values')
    op.drop_table('attention_values')
    op.drop_index(op.f('ix_ai_productivity_boosts_id'), table_name='ai_productivity_boosts')
    op.drop_table('ai_productivity_boosts')
    op.drop_index(op.f('ix_ai_efficiencies_id'), table_name='ai_efficiencies')
    op.drop_table('ai_efficiencies')
    # ### end Alembic commands ###
