"""add arm_config table

Revision ID: b00a44e2b823
Revises: 225e46d1847f
Create Date: 2026-04-19 12:31:15.141536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b00a44e2b823'
down_revision: Union[str, None] = '225e46d1847f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arm_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('analysis_model', sa.String(length=128), nullable=False),
    sa.Column('generation_model', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('generation_temperature', sa.Float(), nullable=False),
    sa.Column('max_chunk_tokens', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('retry_limit', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('max_file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('allowed_extensions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('task_complexity_default', sa.Integer(), nullable=False),
    sa.Column('task_urgency_default', sa.Integer(), nullable=False),
    sa.Column('resource_cost_default', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arm_config')
    # ### end Alembic commands ###
