"""Masterplan

Revision ID: b72d3989ae01
Revises: 1a085e32efd4
Create Date: 2026-02-14 19:16:27.941131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72d3989ae01'
down_revision: Union[str, None] = '1a085e32efd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_plans', sa.Column('wcu_target', sa.Float(), nullable=True))
    op.add_column('master_plans', sa.Column('revenue_target', sa.Float(), nullable=True))
    op.add_column('master_plans', sa.Column('books_required', sa.Integer(), nullable=True))
    op.add_column('master_plans', sa.Column('platform_required', sa.Boolean(), nullable=True))
    op.add_column('master_plans', sa.Column('studio_required', sa.Boolean(), nullable=True))
    op.add_column('master_plans', sa.Column('playbooks_required', sa.Integer(), nullable=True))
    op.add_column('master_plans', sa.Column('total_wcu', sa.Float(), nullable=True))
    op.add_column('master_plans', sa.Column('gross_revenue', sa.Float(), nullable=True))
    op.add_column('master_plans', sa.Column('books_published', sa.Integer(), nullable=True))
    op.add_column('master_plans', sa.Column('platform_live', sa.Boolean(), nullable=True))
    op.add_column('master_plans', sa.Column('studio_ready', sa.Boolean(), nullable=True))
    op.add_column('master_plans', sa.Column('active_playbooks', sa.Integer(), nullable=True))
    op.add_column('master_plans', sa.Column('phase', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_plans', 'phase')
    op.drop_column('master_plans', 'active_playbooks')
    op.drop_column('master_plans', 'studio_ready')
    op.drop_column('master_plans', 'platform_live')
    op.drop_column('master_plans', 'books_published')
    op.drop_column('master_plans', 'gross_revenue')
    op.drop_column('master_plans', 'total_wcu')
    op.drop_column('master_plans', 'playbooks_required')
    op.drop_column('master_plans', 'studio_required')
    op.drop_column('master_plans', 'platform_required')
    op.drop_column('master_plans', 'books_required')
    op.drop_column('master_plans', 'revenue_target')
    op.drop_column('master_plans', 'wcu_target')
    # ### end Alembic commands ###
