"""sync_schema_model_drift

Revision ID: 045921eda2ca
Revises: g5h6i7j8k9l0
Create Date: 2026-04-01 22:33:19.959590

SAFETY REVIEW — changes made to the autogenerated output
=========================================================
1. REMOVED  op.drop_index('ix_memory_nodes_embedding_hnsw')
   WHY: This is a pgvector HNSW index created explicitly in migration
   f3a4b5c6d7e8_add_memory_nodes_embedding_hnsw.  Autogenerate cannot
   understand custom index types and incorrectly marks it for removal.
   Dropping it would destroy semantic vector-similarity search (every
   embedding query would fall back to a full table scan).

2. REMOVED  op.drop_constraint('capabilities_name_key', type_='unique')
   WHY: No replacement unique index was generated for capabilities.name.
   The model declares unique=True on name; this constraint IS the
   enforcement.  Dropping it would silently remove uniqueness guarantees
   with no substitute.

3. REMOVED  op.drop_constraint('goal_states_goal_id_key', type_='unique')
   WHY: Same as #2 — GoalState.goal_id has unique=True; this constraint
   is the enforcement.  Autogenerate found a naming-convention mismatch
   but produced no replacement.

4. REPLACED drop_index(ix_eu_tenant_id) + create_index(ix_execution_units_tenant_id)
   with ALTER INDEX ... RENAME TO
   WHY: The index is identical (same column, same options); only the name
   changed between the sprint_os_layer migration (custom name) and the
   Alembic f() convention.  A RENAME avoids a full index rebuild on what
   may be a large table in production.

5. ADDED postgresql_using clause to strategies.updated_at type change
   WHY: Changing TIMESTAMP WITH TIME ZONE → TIMESTAMP WITHOUT TIME ZONE
   requires an explicit USING expression in PostgreSQL to ensure wall-clock
   values are preserved rather than rejected with a cast error.

6. ADDED _assert_no_nulls() guards before each NOT NULL enforcement
   WHY: ALTER COLUMN ... SET NOT NULL will fail with a constraint-violation
   error if any existing rows have NULL in the column.  The guard raises a
   clear RuntimeError before PostgreSQL even sees the DDL, giving the DBA
   actionable information (row count) to fix the data first.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '045921eda2ca'
down_revision: Union[str, None] = 'g5h6i7j8k9l0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _assert_no_nulls(table: str, column: str) -> None:
    """Raise RuntimeError if any rows carry NULL in *column*.

    Called immediately before op.alter_column(..., nullable=False) so the
    migration fails early with a human-readable message instead of a cryptic
    PostgreSQL NOT NULL constraint-violation error mid-DDL.
    """
    conn = op.get_bind()
    result = conn.execute(
        sa.text(f"SELECT COUNT(*) FROM {table} WHERE {column} IS NULL")
    )
    count = result.scalar()
    if count:
        raise RuntimeError(
            f"Migration aborted: {count} row(s) in '{table}' have "
            f"NULL in '{column}'.  Backfill or delete those rows, then "
            f"re-run the migration."
        )


# ---------------------------------------------------------------------------
# Upgrade
# ---------------------------------------------------------------------------

def upgrade() -> None:
    """Upgrade schema — safe, production-ready drift sync."""

    # ── agent_events.user_id ────────────────────────────────────────────────
    # Enforce NOT NULL (model: AgentEvent.user_id nullable=False).
    # Guard ensures no existing NULL rows cause a hard PostgreSQL error.
    _assert_no_nulls("agent_events", "user_id")
    op.alter_column(
        'agent_events', 'user_id',
        existing_type=sa.UUID(),
        nullable=False,
    )

    # ── agent_runs: index on agent_type ─────────────────────────────────────
    # Model: AgentRun.agent_type = Column(..., index=True)
    op.create_index(
        op.f('ix_agent_runs_agent_type'), 'agent_runs', ['agent_type'],
        unique=False,
    )

    # ── agents: index on owner_user_id ──────────────────────────────────────
    # Model: Agent.owner_user_id = Column(..., index=True)
    op.create_index(
        op.f('ix_agents_owner_user_id'), 'agents', ['owner_user_id'],
        unique=False,
    )

    # ── automation_logs: drop source / status indexes ───────────────────────
    # AutomationLog model does not declare index=True on source or status.
    # PERF NOTE: range queries on these columns will use sequential scans.
    op.drop_index(op.f('ix_automation_logs_source'), table_name='automation_logs')
    op.drop_index(op.f('ix_automation_logs_status'), table_name='automation_logs')

    # ── background_task_leases: consolidate constraint + index ──────────────
    # Prior migration created both a named unique constraint
    # (background_task_leases_name_key) and a non-unique named index
    # (ix_background_task_leases_name) on the same column.
    # Model: name = Column(..., unique=True, index=True) — one unique index
    # is sufficient.  All three DDL steps run in the same transaction, so
    # uniqueness is never absent from PostgreSQL's perspective.
    op.drop_constraint(
        op.f('background_task_leases_name_key'),
        'background_task_leases',
        type_='unique',
    )
    op.drop_index(
        op.f('ix_background_task_leases_name'),
        table_name='background_task_leases',
    )
    op.create_index(
        op.f('ix_background_task_leases_name'),
        'background_task_leases', ['name'],
        unique=True,
    )

    # ── capabilities.name: SKIP unique-constraint drop ──────────────────────
    # AUTOGENERATE BUG: autogenerate detected a naming-convention mismatch on
    # 'capabilities_name_key' but generated no replacement unique index.
    # Capability.name has unique=True; this constraint IS that enforcement.
    # Leaving it in place preserves data integrity.

    # ── execution_units.tenant_id: RENAME index ─────────────────────────────
    # Old name: ix_eu_tenant_id  (sprint_os_layer migration, custom naming)
    # New name: ix_execution_units_tenant_id  (Alembic f() convention)
    # RENAME avoids a full index rebuild — content is identical.
    op.execute(
        "ALTER INDEX IF EXISTS ix_eu_tenant_id "
        "RENAME TO ix_execution_units_tenant_id"
    )

    # ── flow_runs: drop status / waiting_for indexes ─────────────────────────
    # FlowRun model does not declare index=True on status or waiting_for.
    # PERF NOTE: active-run dashboards that filter on status will be slower.
    op.drop_index(op.f('ix_flow_runs_status'), table_name='flow_runs')
    op.drop_index(op.f('ix_flow_runs_waiting_for'), table_name='flow_runs')

    # ── goal_states.goal_id: SKIP unique-constraint drop ────────────────────
    # AUTOGENERATE BUG: same as capabilities_name_key — no replacement unique
    # index was generated.  GoalState.goal_id has unique=True; dropping
    # 'goal_states_goal_id_key' would silently remove that guarantee.

    # ── loop_adjustments.user_id ────────────────────────────────────────────
    # Enforce NOT NULL (model: LoopAdjustment.user_id nullable=False).
    _assert_no_nulls("loop_adjustments", "user_id")
    op.alter_column(
        'loop_adjustments', 'user_id',
        existing_type=sa.UUID(),
        nullable=False,
    )

    # ── memory_metrics.user_id ──────────────────────────────────────────────
    # Enforce NOT NULL (model: MemoryMetric.user_id nullable=False).
    _assert_no_nulls("memory_metrics", "user_id")
    op.alter_column(
        'memory_metrics', 'user_id',
        existing_type=sa.UUID(),
        nullable=False,
    )

    # ── memory_nodes HNSW index: DO NOT DROP ────────────────────────────────
    # AUTOGENERATE CANNOT HANDLE HNSW INDEXES.
    # ix_memory_nodes_embedding_hnsw was created explicitly in migration
    # f3a4b5c6d7e8_add_memory_nodes_embedding_hnsw using pgvector HNSW syntax.
    # It is intentionally preserved here — the SQLAlchemy model does not
    # describe it (autogenerate limitation), but it must exist for semantic
    # similarity search to perform within SLA.

    # ── memory_nodes: add user_id and visibility indexes ────────────────────
    # Model: MemoryNodeModel.user_id index=True, .visibility index=True
    op.create_index(
        op.f('ix_memory_nodes_user_id'), 'memory_nodes', ['user_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_memory_nodes_visibility'), 'memory_nodes', ['visibility'],
        unique=False,
    )

    # ── memory_traces.user_id ───────────────────────────────────────────────
    # Enforce NOT NULL (model: MemoryTrace.user_id nullable=False).
    _assert_no_nulls("memory_traces", "user_id")
    op.alter_column(
        'memory_traces', 'user_id',
        existing_type=sa.UUID(),
        nullable=False,
    )

    # ── nodus_scheduled_jobs: drop composite (user_id, is_active) index ─────
    # NodusScheduledJob model has separate single-column indexes on user_id
    # and is_active; the composite was added by sprint_nodus_scheduler.
    op.drop_index(
        op.f('ix_nodus_scheduled_jobs_user_active'),
        table_name='nodus_scheduled_jobs',
    )

    # ── nodus_trace_events: drop composite (trace_id, sequence) index ───────
    # NodusTraceEvent model has a single-column index on trace_id; sequence
    # is unindexed.  The composite was added by sprint_nodus_observability.
    op.drop_index(
        op.f('ix_nodus_trace_events_trace_id_sequence'),
        table_name='nodus_trace_events',
    )

    # ── playbooks: relax NOT NULL on steps and success_rate ─────────────────
    # Model PlaybookDB declares no nullable=False on these columns —
    # SQLAlchemy defaults to nullable=True.
    op.alter_column(
        'playbooks', 'steps',
        existing_type=sa.TEXT(),
        nullable=True,
    )
    op.alter_column(
        'playbooks', 'success_rate',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::double precision"),
    )

    # ── request_metrics: drop composite index, add PK alias index ───────────
    # Model indexes path and created_at separately.
    # ix_request_metrics_id aligns with id = Column(Integer, ..., index=True).
    # NOTE: the PK already has a btree index (request_metrics_pkey); this
    # creates a named alias — harmless but technically redundant.
    op.drop_index(
        op.f('ix_request_metrics_path_created_at'),
        table_name='request_metrics',
    )
    op.create_index(
        op.f('ix_request_metrics_id'), 'request_metrics', ['id'],
        unique=False,
    )

    # ── score_history: drop composite (user_id, calculated_at) index ────────
    # Model has a single-column index on user_id; calculated_at is unindexed.
    op.drop_index(
        op.f('ix_score_history_user_calculated'),
        table_name='score_history',
    )

    # ── score_snapshots: relax NOT NULL, add PK alias index ─────────────────
    # ScoreSnapshotDB declares no nullable=False on these columns.
    # ix_score_snapshots_id: same reasoning as ix_request_metrics_id above.
    op.alter_column(
        'score_snapshots', 'drop_point_id',
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        'score_snapshots', 'timestamp',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        'score_snapshots', 'narrative_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'score_snapshots', 'velocity_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        'score_snapshots', 'spread_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.create_index(
        op.f('ix_score_snapshots_id'), 'score_snapshots', ['id'],
        unique=False,
    )

    # ── strategies: reconcile with StrategyDB (db/models/strategy.py) ───────
    # StrategyDB uses extend_existing=True and is the authoritative definition.
    #
    # a) intent_type / flow / name / success_rate → nullable=True
    #    StrategyDB declares all of these as nullable=True; the DB currently
    #    enforces NOT NULL from the recreate_strategies migration.
    #
    # b) updated_at: TIMESTAMP WITH TIME ZONE → TIMESTAMP WITHOUT TIME ZONE
    #    StrategyDB.updated_at = Column(DateTime, ...) — no timezone.
    #    SAFETY: explicit AT TIME ZONE 'UTC' USING clause converts stored
    #    wall-clock values cleanly without data loss.
    #
    # c) Drop FK fk_strategies_user_id_users.
    #    StrategyDB.user_id carries no ForeignKey(); the constraint is stale.
    op.alter_column(
        'strategies', 'intent_type',
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        'strategies', 'flow',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        'strategies', 'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text('now()'),
        postgresql_using="updated_at AT TIME ZONE 'UTC'",
    )
    op.alter_column(
        'strategies', 'name',
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        'strategies', 'success_rate',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_constraint(
        op.f('fk_strategies_user_id_users'), 'strategies',
        type_='foreignkey',
    )

    # ── system_events: add composite (agent_id, timestamp) index ────────────
    # Defined in SystemEvent.__table_args__:
    #   Index("ix_system_events_agent_id_timestamp", "agent_id", "timestamp")
    op.create_index(
        'ix_system_events_agent_id_timestamp',
        'system_events', ['agent_id', 'timestamp'],
        unique=False,
    )

    # ── tasks.dependency_type: relax NOT NULL → nullable ────────────────────
    # Model: dependency_type = Column(String, default="hard") — no nullable=False.
    # Server default 'hard' is preserved; new rows still get the correct default.
    op.alter_column(
        'tasks', 'dependency_type',
        existing_type=sa.VARCHAR(length=32),
        nullable=True,
        existing_server_default=sa.text("'hard'::character varying"),
    )

    # ── user_scores: relax NOT NULL on all KPI / metadata columns ───────────
    # UserScore declares Float/Integer/String columns without nullable=False
    # (SQLAlchemy default = nullable=True).
    # Server defaults (0 / 'v1') are preserved so new rows are still valid.
    op.alter_column(
        'user_scores', 'master_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'execution_speed_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'decision_efficiency_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'ai_productivity_boost_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'focus_quality_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'masterplan_progress_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'score_version',
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'v1'::character varying"),
    )
    op.alter_column(
        'user_scores', 'data_points_used',
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text('0'),
    )


# ---------------------------------------------------------------------------
# Downgrade
# ---------------------------------------------------------------------------

def downgrade() -> None:
    """Downgrade schema — reverses all upgrade() operations."""

    # ── user_scores: restore NOT NULL ───────────────────────────────────────
    op.alter_column(
        'user_scores', 'data_points_used',
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text('0'),
    )
    op.alter_column(
        'user_scores', 'score_version',
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'v1'::character varying"),
    )
    op.alter_column(
        'user_scores', 'masterplan_progress_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'focus_quality_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'ai_productivity_boost_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'decision_efficiency_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'execution_speed_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'user_scores', 'master_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )

    # ── tasks.dependency_type: restore NOT NULL ──────────────────────────────
    op.alter_column(
        'tasks', 'dependency_type',
        existing_type=sa.VARCHAR(length=32),
        nullable=False,
        existing_server_default=sa.text("'hard'::character varying"),
    )

    # ── system_events: drop agent_id+timestamp composite index ──────────────
    op.drop_index('ix_system_events_agent_id_timestamp', table_name='system_events')

    # ── strategies: restore FK, NOT NULL, and TIMESTAMP WITH TIME ZONE ───────
    op.create_foreign_key(
        op.f('fk_strategies_user_id_users'),
        'strategies', 'users',
        ['user_id'], ['id'],
        ondelete='SET NULL',
    )
    op.alter_column(
        'strategies', 'success_rate',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'strategies', 'name',
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        'strategies', 'updated_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text('now()'),
        postgresql_using="updated_at::timestamptz",
    )
    op.alter_column(
        'strategies', 'flow',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        'strategies', 'intent_type',
        existing_type=sa.VARCHAR(),
        nullable=False,
    )

    # ── score_snapshots: restore NOT NULL, drop PK alias index ──────────────
    op.drop_index(op.f('ix_score_snapshots_id'), table_name='score_snapshots')
    op.alter_column(
        'score_snapshots', 'spread_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'score_snapshots', 'velocity_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'score_snapshots', 'narrative_score',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        'score_snapshots', 'timestamp',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
    )
    op.alter_column(
        'score_snapshots', 'drop_point_id',
        existing_type=sa.VARCHAR(),
        nullable=False,
    )

    # ── score_history: restore composite (user_id, calculated_at) index ─────
    op.create_index(
        op.f('ix_score_history_user_calculated'),
        'score_history', ['user_id', 'calculated_at'],
        unique=False,
    )

    # ── request_metrics: restore composite index, drop PK alias index ────────
    op.drop_index(op.f('ix_request_metrics_id'), table_name='request_metrics')
    op.create_index(
        op.f('ix_request_metrics_path_created_at'),
        'request_metrics', ['path', 'created_at'],
        unique=False,
    )

    # ── playbooks: restore NOT NULL ──────────────────────────────────────────
    op.alter_column(
        'playbooks', 'success_rate',
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::double precision"),
    )
    op.alter_column(
        'playbooks', 'steps',
        existing_type=sa.TEXT(),
        nullable=False,
    )

    # ── nodus_trace_events: restore composite (trace_id, sequence) index ─────
    op.create_index(
        op.f('ix_nodus_trace_events_trace_id_sequence'),
        'nodus_trace_events', ['trace_id', 'sequence'],
        unique=False,
    )

    # ── nodus_scheduled_jobs: restore composite (user_id, is_active) index ───
    op.create_index(
        op.f('ix_nodus_scheduled_jobs_user_active'),
        'nodus_scheduled_jobs', ['user_id', 'is_active'],
        unique=False,
    )

    # ── memory_traces.user_id: restore nullable ──────────────────────────────
    op.alter_column(
        'memory_traces', 'user_id',
        existing_type=sa.UUID(),
        nullable=True,
    )

    # ── memory_nodes: drop user_id and visibility indexes ────────────────────
    # NOTE: HNSW index was NOT dropped in upgrade — nothing to restore here.
    op.drop_index(op.f('ix_memory_nodes_visibility'), table_name='memory_nodes')
    op.drop_index(op.f('ix_memory_nodes_user_id'), table_name='memory_nodes')

    # ── memory_metrics.user_id: restore nullable ─────────────────────────────
    op.alter_column(
        'memory_metrics', 'user_id',
        existing_type=sa.UUID(),
        nullable=True,
    )

    # ── loop_adjustments.user_id: restore nullable ───────────────────────────
    op.alter_column(
        'loop_adjustments', 'user_id',
        existing_type=sa.UUID(),
        nullable=True,
    )

    # ── goal_states: nothing to downgrade (constraint drop was skipped) ───────

    # ── flow_runs: restore status and waiting_for indexes ────────────────────
    op.create_index(
        op.f('ix_flow_runs_waiting_for'), 'flow_runs', ['waiting_for'],
        unique=False,
    )
    op.create_index(
        op.f('ix_flow_runs_status'), 'flow_runs', ['status'],
        unique=False,
    )

    # ── execution_units.tenant_id: rename index back ─────────────────────────
    op.execute(
        "ALTER INDEX IF EXISTS ix_execution_units_tenant_id "
        "RENAME TO ix_eu_tenant_id"
    )

    # ── capabilities: nothing to downgrade (constraint drop was skipped) ──────

    # ── background_task_leases: restore separate constraint + non-unique index
    op.drop_index(
        op.f('ix_background_task_leases_name'),
        table_name='background_task_leases',
    )
    op.create_index(
        op.f('ix_background_task_leases_name'),
        'background_task_leases', ['name'],
        unique=False,
    )
    op.create_unique_constraint(
        op.f('background_task_leases_name_key'),
        'background_task_leases', ['name'],
        postgresql_nulls_not_distinct=False,
    )

    # ── automation_logs: restore source and status indexes ───────────────────
    op.create_index(
        op.f('ix_automation_logs_status'), 'automation_logs', ['status'],
        unique=False,
    )
    op.create_index(
        op.f('ix_automation_logs_source'), 'automation_logs', ['source'],
        unique=False,
    )

    # ── agents: drop owner_user_id index ─────────────────────────────────────
    op.drop_index(op.f('ix_agents_owner_user_id'), table_name='agents')

    # ── agent_runs: drop agent_type index ────────────────────────────────────
    op.drop_index(op.f('ix_agent_runs_agent_type'), table_name='agent_runs')

    # ── agent_events.user_id: restore nullable ───────────────────────────────
    op.alter_column(
        'agent_events', 'user_id',
        existing_type=sa.UUID(),
        nullable=True,
    )
