"""Regenerate freelance automation tables

Revision ID: 05502a7f9fe8
Revises: 825fc6015dda
Create Date: 2025-10-21 17:07:50.436899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05502a7f9fe8'
down_revision: Union[str, None] = '825fc6015dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freelance_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('project_details', sa.Text(), nullable=True),
    sa.Column('ai_output', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freelance_orders_id'), 'freelance_orders', ['id'], unique=False)
    op.create_table('revenue_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('avg_execution_time', sa.Float(), nullable=True),
    sa.Column('income_efficiency', sa.Float(), nullable=True),
    sa.Column('ai_productivity_boost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_metrics_id'), 'revenue_metrics', ['id'], unique=False)
    op.create_table('client_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['freelance_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_feedback_id'), 'client_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_feedback_id'), table_name='client_feedback')
    op.drop_table('client_feedback')
    op.drop_index(op.f('ix_revenue_metrics_id'), table_name='revenue_metrics')
    op.drop_table('revenue_metrics')
    op.drop_index(op.f('ix_freelance_orders_id'), table_name='freelance_orders')
    op.drop_table('freelance_orders')
    # ### end Alembic commands ###
