"""extend masterplan for genesis lock

Revision ID: 390e474b9ff0
Revises: 0ffe8ba14fb8
Create Date: 2026-02-16 13:12:53.611868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390e474b9ff0'
down_revision: Union[str, None] = '0ffe8ba14fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_plans', sa.Column('structure_json', sa.JSON(), nullable=True))
    op.add_column('master_plans', sa.Column('posture', sa.String(), nullable=True))
    op.add_column('master_plans', sa.Column('version_label', sa.String(), nullable=True))
    op.add_column('master_plans', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('master_plans', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('master_plans', sa.Column('linked_genesis_session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'master_plans', 'master_plans', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'master_plans', 'genesis_sessions', ['linked_genesis_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_plans', type_='foreignkey')
    op.drop_constraint(None, 'master_plans', type_='foreignkey')
    op.drop_column('master_plans', 'linked_genesis_session_id')
    op.drop_column('master_plans', 'parent_id')
    op.drop_column('master_plans', 'locked_at')
    op.drop_column('master_plans', 'version_label')
    op.drop_column('master_plans', 'posture')
    op.drop_column('master_plans', 'structure_json')
    # ### end Alembic commands ###
