"""add activated_at

Revision ID: af746d976e73
Revises: 390e474b9ff0
Create Date: 2026-02-16 14:12:14.072205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af746d976e73'
down_revision: Union[str, None] = '390e474b9ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_plans', sa.Column('activated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_plans', 'activated_at')
    # ### end Alembic commands ###
