"""Register ARM tables properly

Revision ID: bad4f7003aa5
Revises: 0cea8869744b
Create Date: 2025-10-21 18:41:25.843594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad4f7003aa5'
down_revision: Union[str, None] = '0cea8869744b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arm_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arm_configs_id'), 'arm_configs', ['id'], unique=False)
    op.create_table('arm_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('runtime', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arm_runs_id'), 'arm_runs', ['id'], unique=False)
    op.create_table('arm_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['arm_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arm_logs_id'), 'arm_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arm_logs_id'), table_name='arm_logs')
    op.drop_table('arm_logs')
    op.drop_index(op.f('ix_arm_runs_id'), table_name='arm_runs')
    op.drop_table('arm_runs')
    op.drop_index(op.f('ix_arm_configs_id'), table_name='arm_configs')
    op.drop_table('arm_configs')
    # ### end Alembic commands ###
