"""add bridge user events

Revision ID: cb417760d319
Revises: 64b531720229
Create Date: 2026-03-21 23:27:43.589657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb417760d319'
down_revision: Union[str, None] = '64b531720229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'bridge_user_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_name', sa.String(), nullable=False),
        sa.Column('origin', sa.String(), nullable=False),
        sa.Column('raw_timestamp', sa.String(), nullable=True),
        sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_bridge_user_events_origin'), 'bridge_user_events', ['origin'], unique=False)
    op.create_index(op.f('ix_bridge_user_events_user_name'), 'bridge_user_events', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bridge_user_events_user_name'), table_name='bridge_user_events')
    op.drop_index(op.f('ix_bridge_user_events_origin'), table_name='bridge_user_events')
    op.drop_table('bridge_user_events')
    # ### end Alembic commands ###
