"""watcher_signals_table

Creates watcher_signals table for A.I.N.D.Y. Watcher signal events.

Columns:
  id               — auto-increment PK
  signal_type      — session_started | session_ended | distraction_detected |
                     focus_achieved | context_switch | heartbeat
  session_id       — UUID string grouping signals within one work session
  app_name         — active application name at signal time
  window_title     — active window title at signal time (nullable)
  activity_type    — work | communication | distraction | idle | unknown
  signal_timestamp — UTC timestamp when signal was generated by watcher
  received_at      — UTC timestamp when signal was received by API
  duration_seconds — session duration in seconds (session_ended only)
  focus_score      — 0.0–1.0 focused_time/total_time (session_ended only)
  metadata         — JSONB for extra fields (distraction_category, recovery_seconds, etc.)

Revision ID: d7e6f5a4b3c2
Revises: c6e5d4f3b2a1
Create Date: 2026-03-24
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB

revision = "d7e6f5a4b3c2"
down_revision = "c6e5d4f3b2a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "watcher_signals",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("signal_type", sa.String(64), nullable=False),
        sa.Column("session_id", sa.String(64), nullable=False),
        sa.Column("app_name", sa.String(255), nullable=False),
        sa.Column("window_title", sa.Text(), nullable=True),
        sa.Column("activity_type", sa.String(32), nullable=False),
        sa.Column("signal_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("focus_score", sa.Float(), nullable=True),
        sa.Column("signal_metadata", JSONB(), nullable=True),
    )
    op.create_index(
        "ix_watcher_signals_signal_type", "watcher_signals", ["signal_type"]
    )
    op.create_index(
        "ix_watcher_signals_session_id", "watcher_signals", ["session_id"]
    )
    op.create_index(
        "ix_watcher_signals_signal_timestamp", "watcher_signals", ["signal_timestamp"]
    )
    op.create_index(
        "ix_watcher_signals_session_type",
        "watcher_signals",
        ["session_id", "signal_type"],
    )
    op.create_index(
        "ix_watcher_signals_received_at", "watcher_signals", ["received_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_watcher_signals_received_at", table_name="watcher_signals")
    op.drop_index("ix_watcher_signals_session_type", table_name="watcher_signals")
    op.drop_index("ix_watcher_signals_signal_timestamp", table_name="watcher_signals")
    op.drop_index("ix_watcher_signals_session_id", table_name="watcher_signals")
    op.drop_index("ix_watcher_signals_signal_type", table_name="watcher_signals")
    op.drop_table("watcher_signals")
